[package]
name = "tsp-rs"
license = "MIT"
version = "0.1.0"
authors = ["stoksc <stoksc.rs@gmail.com>"]
description = "Traveling salesman problem algorithm implementations"
edition = "2018"

[dependencies]
rand = "0.6.5"